Feat/bubble chart
SpoonX/aurelia-charts-c3 pull request #4
Opened 2016-10-03 09:29 UTC by bas080

- Changes to api
- Bubble chart feature
- New build

@RWOverdijk ready for a merge and a publish.

2016-10-04 08:43 UTC, VMBindraban commented
Don't include the build into the PR.
Make a new PR for building and version bumping.

2016-10-04 08:47 UTC, VMBindraban approved these changes

2016-10-04 08:47 UTC, VMBindraban commented on src/chart/two-dimensional.js
> +        [label ].concat(dataset.map(this.dimensions[1].value)),
Remove space in the array.

2016-10-04 08:47 UTC, VMBindraban commented on src/chart/three-dimensional.js
> +
Remove newlines

2016-10-04 08:47 UTC, VMBindraban commented on src/chart/one-dimensional.js
> +      return [label].concat(dataset.map(this.dimensions[0].value));
No need for `const`.

2016-10-04 08:47 UTC, VMBindraban commented on src/chart/bubble.js
> +      columns: []
Alignment

2016-10-04 08:47 UTC, VMBindraban requested changes
Pressed wrong button, see feedback.

2016-10-04 10:42 UTC, VMBindraban requested changes

2016-10-04 10:42 UTC, VMBindraban commented on src/chart/one-dimensional.js
> +      return [label].concat(dataset.map(this.dimensions[0].value));
`return [dataset.key].concat(dataset.map(this.dimensions[0].value));`

2016-10-04 10:42 UTC, VMBindraban commented on src/chart/three-dimensional.js
> +        [label ].concat(dataset.map(this.dimensions[1].value)),
Remove space.

2016-10-04 10:42 UTC, VMBindraban commented on src/chart/three-dimensional.js
> +    return this.settings;
`return {columns, xs};`?

2016-10-04 10:42 UTC, VMBindraban commented on src/chart/two-dimensional.js
> +        [label] .concat(dataset.map(this.dimensions[1].value)),
Remove space before `.concat`

2016-10-05 09:21 UTC, bas080 commented on src/chart/two-dimensional.js
> +        [label] .concat(dataset.map(this.dimensions[1].value)),
Reason why I did this is to make it easier to edit and read.

2016-10-05 09:24 UTC, bas080 commented on src/chart/one-dimensional.js
> +      return [label].concat(dataset.map(this.dimensions[0].value));
This has changed in a later version.

2016-10-06 07:27 UTC, VMBindraban requested changes

2016-10-06 07:27 UTC, VMBindraban commented on src/chart/bubble.js
> +      columns: []
Alignment

2016-10-06 07:27 UTC, VMBindraban commented on src/chart/bubble.js
> +import {ThreeDimensional} from './three-dimensional';
Alignment

2016-10-06 07:27 UTC, VMBindraban commented on src/chart/three-dimensional.js
> +import {TwoDimensional} from './two-dimensional';
Alignment

2016-10-06 07:27 UTC, VMBindraban commented on src/chart/three-dimensional.js
> +    this.settings = TwoDimensional.prototype.calculateSettings.call(this);
Alignment and remove newline

2016-10-06 09:11 UTC, VMBindraban approved these changes

2016-10-06 13:45 UTC, RWOverdijk commented
@bas080 @VMBindraban was right. Don't include builds with PRs.

2016-10-06 13:45 UTC, merged